Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.define "web" do |web|
    web.vm.network "private_network", ip: "192.168.56.10"
    web.vm.provision "shell", path: "scripts/setup_web.sh"
  end

  config.vm.define "db" do |db|
    db.vm.network "private_network", ip: "192.168.56.11"
    db.vm.provision "shell", path: "scripts/setup_db.sh"
  end

  config.vm.define "ci" do |ci|
    ci.vm.network "private_network", ip: "192.168.56.12"
    ci.vm.provision "shell", path: "scripts/setup_ci.sh"
  end
end
