Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "public_network", bridge: "enp0s3"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
end
